-- Admin panel: opening-hours overrides + reusable "special week" templates.
-- Run this once in the Supabase SQL editor before the admin panel / new
-- Netlify functions (admin-*.js) will work.
--
-- Assumes the existing `schedule` table uses weekday values
-- monday/tuesday/wednesday/thursday/friday/saturday/sunday (matches
-- get-slots.js / book-slot.js / booking.html's WEEKDAY_NAMES) and that
-- `bookings` has a standard Supabase `id bigint generated by default as
-- identity primary key` (not selected by any existing query, so double
-- check this before running admin-bookings.js / admin-blocks.js against it).

create table if not exists week_templates (
  id bigint generated always as identity primary key,
  name text not null,
  created_at timestamptz not null default now()
);

create table if not exists week_template_days (
  id bigint generated always as identity primary key,
  template_id bigint not null references week_templates(id) on delete cascade,
  weekday text not null check (weekday in ('monday','tuesday','wednesday','thursday','friday','saturday','sunday')),
  is_open boolean not null,
  open_time time,
  close_time time,
  unique (template_id, weekday)
);

create table if not exists schedule_overrides (
  date date primary key,
  is_open boolean not null,
  open_time time,
  close_time time,
  source_template_id bigint references week_templates(id) on delete set null
);
